[server]
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1D9BF0"
font = "sans serif"

[theme.light]
primaryColor = "#1D9BF0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F9F9"
textColor = "#0F1419"

[theme.dark]
primaryColor = "#1D9BF0"
backgroundColor = "#000000"
secondaryBackgroundColor = "#16181C"
textColor = "#E7E9EA"
